### ISSUE TITLE
how do i make it 1 file?

### ISSUE THREAD

**Issue by qizq1337** [mazk5145/KeyAuth-JS-Example#1]
how do i make it 1 file?

**Comment by mazk5145** [comment]
What version Import JS Or CommonJS?

**Comment by qizq1337** [comment]
common js.
btw whats the difference?

**Comment by mazk5145** [comment]
commonjs is common :D, so it usually uses const file = require("????");

importjs is import file from "????"

**Comment by mazk5145** [comment]
no reply
